name: SL Api
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: laravel
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        
    steps:
      - uses: actions/checkout@v1

      - name: Verify MariaDB connection
        image: mysql:5.7
        env:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: laravel]
        ports:
            - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      - run: composer install
      - run: cp .env.example .env
      - run: php artisan cache:clear
      - run: php artisan config:clear
      - run: php artisan key:generate
      - run: php artisan migrate
      - run: ./vendor/bin/phpunit
